# Generated by Django 6.0.1 on 2026-01-15 21:48

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('cards', '0001_initial'),
        ('companies', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CompanyUser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role', models.CharField(choices=[('owner', 'Propietario'), ('admin', 'Administrador'), ('editor', 'Editor'), ('viewer', 'Solo lectura'), ('printer', 'Operador de impresión')], default='editor', max_length=20, verbose_name='Rol')),
                ('department', models.CharField(blank=True, max_length=100, verbose_name='Departamento')),
                ('can_create_templates', models.BooleanField(default=False, verbose_name='Crear plantillas')),
                ('can_edit_templates', models.BooleanField(default=False, verbose_name='Editar plantillas')),
                ('can_delete_templates', models.BooleanField(default=False, verbose_name='Eliminar plantillas')),
                ('can_create_cards', models.BooleanField(default=True, verbose_name='Crear tarjetas')),
                ('can_edit_cards', models.BooleanField(default=False, verbose_name='Editar tarjetas')),
                ('can_delete_cards', models.BooleanField(default=False, verbose_name='Eliminar tarjetas')),
                ('can_export_data', models.BooleanField(default=False, verbose_name='Exportar datos')),
                ('can_manage_users', models.BooleanField(default=False, verbose_name='Gestionar usuarios')),
                ('can_view_reports', models.BooleanField(default=False, verbose_name='Ver reportes')),
                ('receive_notifications', models.BooleanField(default=True, verbose_name='Recibir notificaciones')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de creación')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Última actualización')),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='company_users', to='companies.company')),
                ('default_template', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='cards.cardtemplate', verbose_name='Plantilla predeterminada')),
                ('invited_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='invited_users', to=settings.AUTH_USER_MODEL, verbose_name='Invitado por')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='company_users', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Usuario de empresa',
                'verbose_name_plural': 'Usuarios de empresa',
                'ordering': ['company', 'user'],
                'unique_together': {('user', 'company')},
            },
        ),
    ]
