# Generated by Django 6.0.1 on 2026-01-15 21:48

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Company',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=200, unique=True, verbose_name='Nombre de la empresa')),
                ('slug', models.SlugField(help_text='URL amigable para la empresa', max_length=100, unique=True)),
                ('contact_email', models.EmailField(max_length=254, verbose_name='Email de contacto')),
                ('contact_phone', models.CharField(blank=True, max_length=20, verbose_name='Teléfono')),
                ('contact_person', models.CharField(blank=True, max_length=100, verbose_name='Persona de contacto')),
                ('tax_id', models.CharField(blank=True, max_length=20, verbose_name='RFC/NIF')),
                ('address', models.TextField(blank=True, verbose_name='Dirección')),
                ('city', models.CharField(blank=True, max_length=100)),
                ('country', models.CharField(blank=True, default='México', max_length=100)),
                ('logo', models.ImageField(blank=True, null=True, upload_to='company_logos/', verbose_name='Logotipo')),
                ('primary_color', models.CharField(default='#3B82F6', max_length=7, verbose_name='Color primario')),
                ('secondary_color', models.CharField(default='#1E40AF', max_length=7, verbose_name='Color secundario')),
                ('subscription_plan', models.CharField(choices=[('free', 'Gratuito (100 tarjetas)'), ('basic', 'Básico (1,000 tarjetas)'), ('premium', 'Premium (10,000 tarjetas)'), ('enterprise', 'Enterprise (Ilimitado)')], default='free', max_length=20, verbose_name='Plan de suscripción')),
                ('subscription_start', models.DateField(auto_now_add=True, verbose_name='Inicio de suscripción')),
                ('subscription_end', models.DateField(blank=True, null=True, verbose_name='Fin de suscripción')),
                ('api_key', models.UUIDField(default=uuid.uuid4, editable=False, unique=True, verbose_name='Clave API')),
                ('webhook_url', models.URLField(blank=True, verbose_name='URL para Webhooks')),
                ('is_active', models.BooleanField(default=True, verbose_name='Activa')),
                ('is_verified', models.BooleanField(default=False, verbose_name='Verificada')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de creación')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Última actualización')),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_companies', to=settings.AUTH_USER_MODEL, verbose_name='Creado por')),
            ],
            options={
                'verbose_name': 'Empresa',
                'verbose_name_plural': 'Empresas',
                'ordering': ['name'],
                'indexes': [models.Index(fields=['api_key'], name='companies_c_api_key_3eaf1a_idx'), models.Index(fields=['is_active'], name='companies_c_is_acti_03043b_idx'), models.Index(fields=['subscription_plan'], name='companies_c_subscri_e613aa_idx')],
            },
        ),
    ]
