# Generated by Django 6.0.1 on 2026-01-15 21:48

import django.core.validators
import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('companies', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CardTemplate',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100, verbose_name='Nombre de la plantilla')),
                ('description', models.TextField(blank=True, verbose_name='Descripción')),
                ('version', models.PositiveIntegerField(default=1, verbose_name='Versión')),
                ('width_mm', models.FloatField(default=85.6, validators=[django.core.validators.MinValueValidator(50), django.core.validators.MaxValueValidator(100)], verbose_name='Ancho (mm)')),
                ('height_mm', models.FloatField(default=53.98, validators=[django.core.validators.MinValueValidator(50), django.core.validators.MaxValueValidator(100)], verbose_name='Alto (mm)')),
                ('corner_radius_mm', models.FloatField(default=3.18, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(10)], verbose_name='Radio de esquinas (mm)')),
                ('dpi', models.IntegerField(choices=[(150, '150 DPI'), (300, '300 DPI'), (600, '600 DPI')], default=300, verbose_name='Resolución')),
                ('background_type', models.CharField(choices=[('color', 'Color sólido'), ('image', 'Imagen'), ('gradient', 'Gradiente')], default='color', max_length=10, verbose_name='Tipo de fondo')),
                ('background_color', models.CharField(default='#FFFFFF', max_length=7, verbose_name='Color de fondo')),
                ('background_image', models.ImageField(blank=True, null=True, upload_to='template_backgrounds/', verbose_name='Imagen de fondo')),
                ('background_opacity', models.FloatField(default=1.0, validators=[django.core.validators.MinValueValidator(0.0), django.core.validators.MaxValueValidator(1.0)], verbose_name='Opacidad del fondo')),
                ('elements', models.JSONField(default=dict, verbose_name='Elementos de diseño')),
                ('fields_config', models.JSONField(default=dict, verbose_name='Configuración de campos')),
                ('is_default', models.BooleanField(default=False, verbose_name='Plantilla predeterminada')),
                ('is_active', models.BooleanField(default=True, verbose_name='Activa')),
                ('has_watermark', models.BooleanField(default=False, verbose_name='Incluir marca de agua')),
                ('watermark_text', models.CharField(blank=True, max_length=100, verbose_name='Texto de marca de agua')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de creación')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Última actualización')),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='templates', to='companies.company')),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_templates', to=settings.AUTH_USER_MODEL, verbose_name='Creado por')),
            ],
            options={
                'verbose_name': 'Plantilla de tarjeta',
                'verbose_name_plural': 'Plantillas de tarjeta',
                'ordering': ['company', 'name'],
            },
        ),
        migrations.CreateModel(
            name='IDCard',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('card_number', models.CharField(db_index=True, max_length=50, unique=True, verbose_name='Número de tarjeta')),
                ('person_name', models.CharField(max_length=200, verbose_name='Nombre completo')),
                ('person_title', models.CharField(blank=True, max_length=100, verbose_name='Puesto/Cargo')),
                ('department', models.CharField(blank=True, max_length=100, verbose_name='Departamento')),
                ('employee_id', models.CharField(blank=True, max_length=50, verbose_name='Número de empleado')),
                ('id_number', models.CharField(db_index=True, max_length=100, verbose_name='Número de identificación')),
                ('id_type', models.CharField(default='employee', max_length=50, verbose_name='Tipo de ID')),
                ('photo', models.ImageField(upload_to='card_photos/', verbose_name='Fotografía')),
                ('signature', models.ImageField(blank=True, null=True, upload_to='signatures/', verbose_name='Firma')),
                ('barcode_type', models.CharField(choices=[('code128', 'Code 128'), ('code39', 'Code 39'), ('qr', 'QR Code'), ('pdf417', 'PDF417')], default='code128', max_length=20)),
                ('barcode_data', models.CharField(max_length=100, verbose_name='Datos para código de barras')),
                ('barcode_image', models.ImageField(upload_to='barcodes/', verbose_name='Imagen de código de barras')),
                ('qr_code', models.ImageField(blank=True, null=True, upload_to='qr_codes/', verbose_name='Código QR')),
                ('issue_date', models.DateField(auto_now_add=True, verbose_name='Fecha de emisión')),
                ('valid_from', models.DateField(blank=True, null=True, verbose_name='Válido desde')),
                ('expiration_date', models.DateField(blank=True, null=True, verbose_name='Fecha de expiración')),
                ('card_type', models.CharField(choices=[('employee', 'Empleado'), ('student', 'Estudiante'), ('visitor', 'Visitante'), ('contractor', 'Contratista'), ('temporary', 'Temporal')], default='employee', max_length=20)),
                ('status', models.CharField(choices=[('draft', 'Borrador'), ('active', 'Activa'), ('expired', 'Expirada'), ('revoked', 'Revocada'), ('lost', 'Perdida'), ('damaged', 'Dañada')], default='active', max_length=20)),
                ('printed', models.BooleanField(default=False, verbose_name='Impresa')),
                ('printed_at', models.DateTimeField(blank=True, null=True, verbose_name='Fecha de impresión')),
                ('printed_count', models.PositiveIntegerField(default=0, verbose_name='Veces impresa')),
                ('composite_image', models.ImageField(blank=True, null=True, upload_to='composite_cards/', verbose_name='Imagen compuesta')),
                ('pdf_file', models.FileField(blank=True, null=True, upload_to='card_pdfs/', verbose_name='Archivo PDF')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de creación')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Última actualización')),
                ('last_accessed', models.DateTimeField(blank=True, null=True, verbose_name='Último acceso')),
                ('metadata', models.JSONField(blank=True, default=dict, verbose_name='Metadatos adicionales')),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cards', to='companies.company')),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_cards', to=settings.AUTH_USER_MODEL, verbose_name='Creado por')),
                ('printed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='printed_cards', to=settings.AUTH_USER_MODEL, verbose_name='Impreso por')),
                ('template', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='cards', to='cards.cardtemplate')),
            ],
            options={
                'verbose_name': 'Tarjeta de identificación',
                'verbose_name_plural': 'Tarjetas de identificación',
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddIndex(
            model_name='cardtemplate',
            index=models.Index(fields=['company', 'is_default'], name='cards_cardt_company_32ce13_idx'),
        ),
        migrations.AddIndex(
            model_name='cardtemplate',
            index=models.Index(fields=['is_active'], name='cards_cardt_is_acti_498e10_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='cardtemplate',
            unique_together={('company', 'name')},
        ),
        migrations.AddIndex(
            model_name='idcard',
            index=models.Index(fields=['card_number'], name='cards_idcar_card_nu_67e0c8_idx'),
        ),
        migrations.AddIndex(
            model_name='idcard',
            index=models.Index(fields=['id_number'], name='cards_idcar_id_numb_c15da6_idx'),
        ),
        migrations.AddIndex(
            model_name='idcard',
            index=models.Index(fields=['company', 'status'], name='cards_idcar_company_e137e5_idx'),
        ),
        migrations.AddIndex(
            model_name='idcard',
            index=models.Index(fields=['expiration_date'], name='cards_idcar_expirat_5e56e7_idx'),
        ),
        migrations.AddIndex(
            model_name='idcard',
            index=models.Index(fields=['created_at'], name='cards_idcar_created_289282_idx'),
        ),
    ]
