# Generated by Django 6.0.1 on 2026-01-19 20:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cards', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='idcard',
            name='barcode_image',
            field=models.ImageField(blank=True, null=True, upload_to='barcodes/', verbose_name='Imagen de código de barras'),
        ),
    ]
